# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--b, pre-deploy, --b, main, --b, deploy, --b, master]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        types: [python]
        args: [--ignore-missing-imports, --install-types, --non-interactive]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
    - id: poetry-check
      args: ["--lock", "-C", "service"]
    - id: poetry-export
      args: ["-C", "service", "--without-hashes", "--without", "dev", "-f", "requirements.txt", "-o", "service/requirements.txt"]
      verbose: true

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
