version: 1

disable_existing_loggers: False

formatters:
  console_f:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_f
    stream: ext://sys.stdout

loggers:
  dom_api:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
